
server:
  port: 9191
  


 
 
  
spring:
  application:
    name: API-GATEWAY  
  cloud:
    gateway:
      routes:
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
        - Path= /user/**   

                             
      - id: DEPARTMENT-SERVICE
        uri: lb://DEPARTMENT-SERVICE
        predicates:
        - Path= /departments/**        
  main:
    web-application-type: reactive 
        




resilience4j:
  circuitbreaker:
    instances:
      userService:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        automatic-transition-from-open-to-half-open-enabled: true
        failure-rate-threshold: 30
        minimum-number-of-calls: 10
        permitted-number-of-calls-in-half-open-state: 15
        wait-duration-in-open-state: 10s
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        
        
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
       include: health
  endpoint:
    health:
      show-details: ALWAYS   
      
      
      
    
    
        